name: Write an interpreter in Zig

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ZIG_VERSION: 0.13.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup zig version ${{ env.ZIG_VERSION }}"
        uses: mlugg/setup-zig@v1
        with:
          version: "${{ env.ZIG_VERSION }}"
      - name: Cache zig
        uses: actions/cache@v3
        env:
          cache-name: zig-cache
        with:
          path: |
            ~/zig
          key: zig-${{ env.cache-name }}
          restore-keys: zig-${{ env.cache-name }}
      - name: Run zig build
        run: rm -rf .zig-cache/ && zig build test --summary all --verbose
      - name: Run zig format
        run: zig fmt --check .
