name: Write an interpreter in Zig

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZIG_VERSION: linux-0.15.0-dev.769+4d7980645

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup zig version ${{ env.ZIG_VERSION }}"
        run: |
          curl -LO https://ziglang.org/builds/zig-x86_64-${{ env.ZIG_VERSION }}.tar.xz
          tar -xf zig-x86_64-${{ env.ZIG_VERSION }}.tar.xz
          echo "$(pwd)/zig-x86_64-${{ env.ZIG_VERSION }}" >> $GITHUB_PATH
      - name: Run zig format
        run: zig fmt --check .
      - name: Run zig tests
        run: zig build test --summary all --verbose
