name: Write an interpreter in Zig

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.15.0-dev.734+adc4418ba

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup zig version ${{ env.ZIG_VERSION }}"
        uses: mlugg/setup-zig@v1
        with:
          version: "${{ env.ZIG_VERSION }}"
      - name: Run zig format
        run: zig fmt --check .
      - name: Run zig tests
        run: zig build test --summary all --verbose
